export const ROUTES = {
  LANDING: '/',
  LEGAL: '/legal',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  CONTACT: '/contact',
  CASE_EVALUATION: '/case-evaluation',
  CASE_RESULTS: '/case-evaluation/results',
  SMS_PROGRAM: '/sms',
  FIXMYNIGHT_PRODUCT: '/fixmynight',
  FIXMYNIGHT_PRICING: '/fixmynight/pricing',
  ADMIN_LOGIN: '/fixmynight/admin',
  ADMIN_FORGOT_PASSWORD: '/fixmynight/admin/forgot-password',
  ADMIN_RESET_PASSWORD: '/fixmynight/admin/reset-password',
  ADMIN_DASHBOARD: '/fixmynight/admin/dashboard',
  ADMIN_CLIENTS: '/fixmynight/admin/clients',
  ADMIN_CLIENT_NEW: '/fixmynight/admin/clients/new',
  ADMIN_CLIENT_DETAIL: (id: string) => `/fixmynight/admin/clients/${id}`,
  ADMIN_SERVICES: '/fixmynight/admin/services',
  PORTAL_ENTRY: '/fixmynight/portal',
  PORTAL_SETUP: '/fixmynight/portal/setup',
  PORTAL_FORGOT_PASSWORD: '/fixmynight/portal/forgot-password',
  PORTAL_LOGIN: (clientId: string) => `/fixmynight/portal/${clientId}`,
  PORTAL_DASHBOARD: (clientId: string) => `/fixmynight/portal/${clientId}/dashboard`,
  PORTAL_CALLS: (clientId: string) => `/fixmynight/portal/${clientId}/calls`,
  PORTAL_SETTINGS: (clientId: string) => `/fixmynight/portal/${clientId}/settings`,
  PORTAL_TEAM: (clientId: string) => `/fixmynight/portal/${clientId}/team`,
} as const;
